steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/rola-db/latam-ro-database', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rola-db/latam-ro-database']

images:
  - 'gcr.io/rola-db/latam-ro-database' 