package main

import (
	"log"
	"net/http"
	"os"
	"time"

	"github.com/gorilla/mux"
	"github.com/joho/godotenv"
	httpSwagger "github.com/swaggo/http-swagger"
	"go.uber.org/zap"

	"teste/config"
	_ "teste/docs" // docs is generated by Swag CLI
	"teste/handlers"
)

// @title           Latam RO Database API
// @version         1.0
// @description     API para consulta de dados do Ragnarok Online
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.basic  BasicAuth

var (
	logger *zap.Logger
	port   = getEnv("APP_PORT", "8080")
	host   = getEnv("HOST", "0.0.0.0")
)

func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

func init() {
	// Carrega variáveis de ambiente
	if err := godotenv.Load(); err != nil {
		log.Printf("Warning: .env file not found")
	}

	var err error
	logger, err = zap.NewProduction()
	if err != nil {
		log.Fatalf("can't initialize zap logger: %v", err)
	}
	defer logger.Sync()
}

func loggingMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		// Log da requisição recebida
		logger.Info("request received",
			zap.String("method", r.Method),
			zap.String("path", r.URL.Path),
			zap.String("remote_addr", r.RemoteAddr),
		)

		next.ServeHTTP(w, r)

		logger.Info("request processed",
			zap.String("method", r.Method),
			zap.String("path", r.URL.Path),
			zap.String("remote_addr", r.RemoteAddr),
			zap.Duration("duration", time.Since(start)),
		)
	})
}

func main() {
	logger.Info("Starting application initialization")

	// Inicializa conexão com o banco de dados
	logger.Info("Connecting to database...")
	db, err := config.NewDatabase(logger)
	if err != nil {
		logger.Fatal("Failed to connect to database",
			zap.Error(err),
		)
	}
	defer db.Close()
	logger.Info("Successfully connected to database")

	router := mux.NewRouter()

	// Middleware
	router.Use(loggingMiddleware)

	// API v1 routes
	api := router.PathPrefix("/api/v1").Subrouter()

	// Initialize handlers
	monsterHandler := handlers.NewMonsterHandler(logger, db)
	imageHandler := handlers.NewImageHandler(logger)

	// Documentation
	api.HandleFunc("/docs", monsterHandler.GetAPIDocs).Methods("GET")
	router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	// Monster routes
	api.HandleFunc("/monsters", monsterHandler.GetMonsters).Methods("GET")
	api.HandleFunc("/monsters/{id}", monsterHandler.GetMonster).Methods("GET")
	api.HandleFunc("/monsters/type/{type}", monsterHandler.GetMonstersByType).Methods("GET")

	// Other routes
	api.HandleFunc("/items", monsterHandler.GetItems).Methods("GET")
	api.HandleFunc("/maps", monsterHandler.GetMaps).Methods("GET")
	api.HandleFunc("/skills", monsterHandler.GetSkills).Methods("GET")
	api.HandleFunc("/npcs", monsterHandler.GetNPCs).Methods("GET")
	api.HandleFunc("/images/upload", imageHandler.UploadImage).Methods("POST")

	// Serve static files
	router.PathPrefix("/images/").Handler(http.StripPrefix("/images/", http.FileServer(http.Dir("static/images"))))
	router.PathPrefix("/").Handler(http.FileServer(http.Dir("./static")))

	// Server configuration
	server := &http.Server{
		Addr:         host + ":" + port,
		Handler:      router,
		ReadTimeout:  15 * time.Second,
		WriteTimeout: 15 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	logger.Info("Server configuration complete",
		zap.String("host", host),
		zap.String("port", port),
	)

	// Start server
	logger.Info("Starting HTTP server...")
	if err := server.ListenAndServe(); err != nil {
		logger.Fatal("Server failed to start",
			zap.Error(err),
		)
	}
}
